#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 22 11:32:16 2020
Example Astar algorithm, works on a 2D list
@author: andrewbrose
"""

class Node ():
    def __init__(self, parent = None, position = None):
        self.parent = parent
        self.position = position
        
        self.g = 0 #distance from the start node
        self.h = 0 #estimated distance left to end node
        self.f = 0 #sum of g and h, total distance
        
    def __eq__ (self, other):
        return self.position == other.position
    
    
#returns all the points on best path to end goal as tuples
def astar(maze, start, end):
    start_node = Node(None, start)
    start_node.g = start_node.h = start_node.f = 0
    end_node = Node(None, end)
    end_node.g = end_node.h = end_node.f = 0
    
    
    open_list = [] #all points
    closed_list = [] #only points that could be on the best path?
    
    #add the start node
    open_list.append(start_node)
    
    #loop until target is found
    while len(open_list) > 0:
        #find current node
        current_node = open_list[0]
        current_index=0
        for index, item in enumerate(open_list):
            #if this item has a smaller distance make that current
            if item.f < current_node.f:
                current_node = item
                current_index = index
        
        #pop current off open list and put it in the closed list (path)
        open_list.pop(current_index)
        closed_list.append(current_node)
        
        #check if end has been reached
        if current_node == end_node:
            path = []
            current = current_node
            #trace back via parent to the start, following the shortest path
            while current is not None:
                path.append(current.position)
                current = current.parent
                
            return path[::-1] #return reversed path
        
        
        #if goal not found, generate potential children
        children = []
        for new_position in [(0, -1), (0,1), (-1, 0), (1, 0), (-1, -1), 
                             (-1, 1), (1, -1), (1, 1)]: #adjacent squares
        
            #Get node position
            node_position = (current_node.position[0] + new_position[0], 
                             current_node.position[1] + new_position[1])
                
            #Make sure within range (if not it will continue -> leave loop)
            if node_position[0] > (len(maze) - 1) or node_position[0] < 0 \
            or node_position[1] > (len(maze[len(maze)-1]) -1) \
            or node_position[1] < 0:
                continue
                
            #make sure walkable terrain (if obstacle end loop?)
            if maze[node_position[0]][node_position[1]] != 0:
                continue
                
            new_node = Node(current_node, node_position)
                
            #Append
            children.append(new_node)
            
            
        #Loop through children
        for child in children:
            
            #Child is on the closed list (change this to skip the big loop)
           
            for closed_child in closed_list:
                if child == closed_child:
                    continue
            
            
            #create the f, g, and h values
            child.g = current_node.g + 1
            #pythag but doesn't worry about the root because all relative
            child.h = ((child.position[0] - end_node.position[0]) ** 2) + \
                ((child.position[1] - end_node.position[1]) ** 2)
            child.f = child.g + child.h
            
            #check if child is already in open list (what do these loops do?)
            
            for open_node in open_list:
                if child == open_node and child.g > open_node.g:
                    continue
            
            #add the child to the open list
            open_list.append (child)
            

def main():
    
    maze = [[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
            [0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
            [0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
            [0, 0, 0, 0, 1, 1, 0, 1, 0, 0],
            [0, 0, 0, 0, 1, 0, 0, 1, 0, 0]]
    
    start = (0, 0)
    end = (9,9)
    
    path = astar(maze, start, end)
    print(path)

if __name__ == '__main__':
    main()
        
        
        
        